title: Robert Desrosiers
logo: /assets/img/2025_profilepic.png
description: Unity XR Software Engineer & AWS Backend Developer (6 Years)
show_downloads: false
theme: jekyll-theme-minimal
plugins:
  - jekyll-sitemap
  - jekyll-seo-tag
  - jemoji
